### ISSUE TITLE
Perper Fabric: Implement support for KEDA external scaler 

### ISSUE THREAD

**Issue by branimirangelov** [obecto/perper#49]
Expose required metrics for KEDA external scaler using GRPC in the transport service.

**Comment by bojidar-bg** [comment]
Was implemented in 2ddac590754c6e08e1d0e5bd75de9a6b73e62ec7 <s>(and subsequently reimplemented a few times)</s>; closing.
Hasn't been tested though, so open a new issue if it doesn't work.
