### ISSUE TITLE
API: Cross-platform / cross-language support

### ISSUE THREAD

**Issue by branimirangelov** [obecto/perper#52]
Add unified API in terms of functionality supporting: 

1. .net core 3.1 (azure function extension);
2. mono 5.12 (azure function extension + custom handler for mono)
3. python 3.6+ (azure function extension + bindings for python language worker)

**Comment by branimirangelov** [comment]
Support for mono 5.12 (.net standard 2.0) will be implemented using [embedio](https://github.com/unosquare/embedio) webserver to listen for requests from Azure Functions Runtime (using Custom Handler). The webserver will be managed within a Singleton (PerperContext) and upon request it will create the corresponding objects (IStream, IContext and etc.).

**Comment by bojidar-bg** [comment]
After removing the hard dependency on Azure functions in [`0.7.0`](https://github.com/obecto/perper/releases/tag/0.7.0), this has been much simpler to implement in each language directly; .NET Core (now 5.0) support remains, Python support was added starting in 01c4f771e550eb37360c600686b181bcf149d88a, and .NET Standard 2.0 support proved unnecessary; therefore this can be closed.
