### ISSUE TITLE
For better readability, returning tuples should contain property names

### ISSUE THREAD

**Issue by aph5nt** [obecto/perper#83]
Proposal: For better readability, returning tuples should contain property names:

       public interface IState
          {
              Task<(bool Exists, T Item)> TryGetAsync<T>(string key);

**Comment by bojidar-bg** [comment]
PerperState fixed in 8746b6ea0f0822bfc941cc2b6ae4992a557d487f, going to doublecheck other classes for tuple returns.

**Comment by bojidar-bg** [comment]
Appears to be fixed as of current master (82f0930d609dda24b787ea839d43336ab9713593), closing! :smiley:
