### ISSUE TITLE
General inquery for the usage of static classes with AsyncLocals versus dependency injection

### ISSUE THREAD

**Issue by bojidar-bg** [obecto/perper#84]
But first, a <s>short</s> bit of history:

* In 0.6, we had interfaces such as `IStream`, `IAgent`, `IState`, `IContext`. The first two need to be used as parameters to calls/streams; the latter two are scoped to the agent's instance.
* However, both `Stream` and `Agent` needed access to services to implement their functionality. In 0.6, this access was implemented by adding functionality to `PerperBinarySerializer` to populate services from an `IServiceProvider` while deserializing.
* As one might guess, this proved hacky, and with the removal of `PerperBinarySerializer` in 0.7, we started passing those services through an `AsyncLocal` while still implementing the same classes.
* Then, `Stream<T>` proved to be an issue for Python support, and we introduced `PerperStream` and `PerperAgent` as low-level DTO objects that are safe to pass to other agents, store in state, and otherwise use when interacting with Ignite.
* However, due to a lack of automated conversion between `PerperStream`/`PerperAgent` and `IStream<>`/`IAgent`, code using Perper 0.7 soon became plagued by manual `((Stream)x).RawStream` and `new Stream<T>(x)` conversions.
* Thus for 0.8, I opted to completely drop `IStream` and `IAgent` in lieu of extension methods; and as `IState` and `IContext` were little more than a formality at this point (single implementation with no state), I got rid of them too.

However, I'm not sure this is the best solution, since it tends to couple Perper code to the underlying Ignite implementation as there are practically no interfaces used. In addition, passing all context through an `AsyncLocal` does not feel like an idiomatic C# solution, unlike using an `IServiceProvider` with DI instead.

Thus, my question is, do you feel there could be a better interface provided by Perper for this? Especially curious about users of Dependency Injection.
Feel free to use this code example to illustrate how it would work:
```cs
// Perper 0.8.0-beta1
class Startup {
    public async Task<PerperStream> RunAsync(PerperStream colors) {
        return await PerperContext.Stream("Cars").StartAsync(colors);
    }
}
class Cars {
    public async IAsyncEnumerable<Car> RunAsync(PerperStream colors) {
        await foreach (var color in colors.EnumerateAsync<Color>()) {
            yield return new Car(color);
        }
    }
}
```

**Comment by branimirangelov** [comment]
Find my answers below:
1. _Coupling with Ignite vs Interfaces_ - I think the coupling with Ignite is okay, we might even allow some abstraction leakage around the agent state support. The guiding principle for me would be to offer the Perper programming in the most simple way (minimum boilerplate). This is the reason for hiding the more generic Ignite model, but again when it fits well we can event expose it directly. The decoupling form Ignite for me it is not a design goal for the project.
2. _Idiomatic vs Cross Platform_ - I think we have to try to be cross-platform as much as possible in the lower layers. Essentially, it is more important to have almost identical C# and Python clients at lower level. Therefore, if using "global" variables (Async Local) produces similar code in Python and C#, then I would vote to continue using it. 
3. _Application Layers vs Lower Layers_ - I think we have to have an application layer that is idiomatic and for this layer we have to use C# DI / IServiceProvider. So essentially, when a developer wants to structure an application, the "default" way is to use standard C# DI / IServiceProvider. This means that the actual function / stream classes will also use C# DI / IServiceProvider. However, the lower layer should continue using AsyncLocal approach, we prototyped such hybrid approach in `feat/di` and I like it - of course it has to be refactored and made cleaner.

**Comment by bojidar-bg** [comment]
@branimirangelov ~

1. That's a good point. I just wanted to make sure, since I had some suspicion that abstracting away from Ignite might be helpful for Apocryph at some point, like if we want agents to use the exact same interface but not access Ignite directly. (Even if that's best handled by #54 anyway.)
2. Right now, the lower level (`Perper.Protocol` / `perper.protocol`) is virtually identical between C# and Python, exposing a `FabricService` class that abstracts the connection to Ignite and GRPC and deals with Fabric's data model. This issue is more about the next layer up, the `Perper.Extentions` layer; it is currently also identical between the two (using `contextvars` instead of `AsyncLocal`-s in Python), but it is not as problematic if it differs between languages.
The only reason we use `AsyncLocal`-s is because we need to access a service from an extension method. If we can avoid the extension method, this will no longer be a necessity.
Note that Python does not need to use `contextvars` because it doesn't have extension methods, and writing `perper.enumerate_items(stream)` is equally convenient whether "perper" is a package that uses context vars or an object holding the connection to Perper.
3. The `Perper.Application` layer can definitely be made to use `IServiceProvider`. The main thing right now is that since `PerperContext`, `PerperState`, `PerperStreamExtensions`, and `PerperAgentExtensions` are all static classes, there virtually nothing to provide through DI for Perper applications except for non-Perper services.
